spring.application.name=springbuild_pawsandfound

spring.datasource.url=jdbc:mysql://localhost:3306/pawsandfound?useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update